DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS overviews CASCADE;
DROP TABLE IF EXISTS loves CASCADE;
DROP TABLE IF EXISTS careers CASCADE;
DROP TABLE IF EXISTS finances CASCADE;
DROP TABLE IF EXISTS images CASCADE;

CREATE TABLE cards (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  family VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE overviews (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  reversed BOOLEAN NOT NULL,
  meaning TEXT NOT NULL,
  keywords VARCHAR(255)
);

CREATE TABLE loves (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  reversed BOOLEAN NOT NULL,
  meaning TEXT NOT NULL,
  keywords VARCHAR(255)
);

CREATE TABLE careers (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  reversed BOOLEAN NOT NULL,
  meaning TEXT NOT NULL,
  keywords VARCHAR(255)
);

CREATE TABLE finances (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  reversed BOOLEAN NOT NULL,
  meaning TEXT NOT NULL,
  keywords VARCHAR(255)
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  deck_name TEXT NOT NULL,
  url TEXT NOT NULL
);